local_backend: true

logo_url: /favicon.svg

backend:
  name: github
  repo: dallay/cvix
  branch: main
  base_url: https://sveltia-cms-auth.yunielacosta738.workers.dev/

publish_mode: editorial_workflow

slug:
  encoding: 'ascii'
  clean_accents: true
  sanitize_replacement: '-'


media_folder: "client/apps/marketing/src/assets/images"  # Location where files will be stored in the repo
public_folder: "client/apps/marketing/src/assets/images"  # The src attribute for uploaded media

i18n:
  structure: 'multiple_folders'
  locales: ['en', 'es']
  default_locale: 'en'


collections:
  - name: 'page'
    label: 'Pages'
    folder: client/apps/marketing/src/pages
    create: true
    slug: '{{slug}}'
    extension: mdx
    i18n: true
    fields:
      - name: 'layout'
        widget: 'hidden'
        default: '@/layouts/Page.astro'
      - name: 'title'
        widget: 'string'
        label: 'Title'
        i18n: true
      - name: 'description'
        widget: 'string'
        label: 'Description'
        i18n: true
      - name: 'body'
        widget: 'markdown'
        label: 'Body'
        i18n: true

  - name: 'pricing'
    label: 'Pricing Plans'
    label_singular: 'Pricing Plan'
    folder: client/apps/marketing/src/data/pricing
    create: true
    slug: '{{title}}'
    extension: json
    i18n: true
    fields:
      - name: 'title'
        widget: 'string'
        label: 'Plan Title'
        i18n: true
      - name: 'description'
        widget: 'string'
        label: 'Plan Description'
        i18n: true
      - name: 'price'
        widget: 'number'
        label: 'Price'
        value_type: 'float'
        min: 0
        i18n: 'duplicate'
      - name: 'interval'
        widget: 'select'
        label: 'Billing Interval'
        options: ['month', 'year']
        default: 'month'
        i18n: 'duplicate'
      - name: 'features'
        widget: 'list'
        label: 'Features'
        i18n: true
        fields:
          - name: 'text'
            widget: 'string'
            label: 'Feature Text'
          - name: 'value'
            widget: 'string'
            label: 'Feature Value'
            required: false
      - name: 'highlighted'
        widget: 'boolean'
        label: 'Highlight this plan'
        required: false
        default: false
        i18n: 'duplicate'
      - name: 'order'
        widget: 'number'
        label: 'Display Order'
        value_type: 'int'
        min: 0
        required: false
        default: 0
        i18n: 'duplicate'

  - name: 'faq'
    label: 'FAQ'
    label_singular: 'FAQ Item'
    folder: client/apps/marketing/src/data/faq
    create: true
    slug: '{{question}}'
    extension: json
    i18n: true
    fields:
      - name: 'question'
        widget: 'string'
        label: 'Question'
        i18n: true
      - name: 'date'
        widget: 'datetime'
        label: 'Publish Date'
        i18n: 'duplicate'
      - name: 'body'
        widget: 'text'
        label: 'Body'
        i18n: true
